// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwelve
NumericVector timesTwelve(NumericVector x);
RcppExport SEXP _Rstringmol_timesTwelve(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwelve(x));
    return rcpp_result_gen;
END_RCPP
}
// doReaction
List doReaction(Rcpp::StringVector seqVector, bool verbose);
RcppExport SEXP _Rstringmol_doReaction(SEXP seqVectorSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type seqVector(seqVectorSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(doReaction(seqVector, verbose));
    return rcpp_result_gen;
END_RCPP
}
// doReactionFP
void doReactionFP(Rcpp::StringVector seqVector, bool verbose);
RcppExport SEXP _Rstringmol_doReactionFP(SEXP seqVectorSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type seqVector(seqVectorSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    doReactionFP(seqVector, verbose);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_mod_foo();

static const R_CallMethodDef CallEntries[] = {
    {"_Rstringmol_timesTwelve", (DL_FUNC) &_Rstringmol_timesTwelve, 1},
    {"_Rstringmol_doReaction", (DL_FUNC) &_Rstringmol_doReaction, 2},
    {"_Rstringmol_doReactionFP", (DL_FUNC) &_Rstringmol_doReactionFP, 2},
    {"_rcpp_module_boot_mod_foo", (DL_FUNC) &_rcpp_module_boot_mod_foo, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rstringmol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
