---
title: "Figures For 'Biology' Paper"
author: "Simon Hickinbotham"
date: "13/07/2020"
output:
  word_document: default
  pdf_document: default
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here's the first figure

```{r seedrep,engine='tikz',fig.width=10, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);

  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 1:}} Replicator reaction at t=40,000};

  % dividing line
  \draw[black!20!white] (-0.1,0) -- (6.5,0);


  %'active molecule'
  \fill[black!40!white] (0,0.5) rectangle (6.4,0.7);
  % copy loop:
  \fill[red!40!white] (4.7,0.5) rectangle (5.2,0.7);
  %bind site
  \draw[red] (1.7,0.5) rectangle (3.0,0.7);

  % 'Execution:' 
  \fill[green] (1.65,0.4) circle (0.05);
  \draw[->] (1.7,0.4) -- (4.7,0.4);

  \fill[red] (4.75,0.4) circle (0.05);
  \draw[-> , draw=red] (4.7,0.4) -- (5.2,0.4); 

  \draw[->] (5.2,0.4) -- (5.9,0.4);
  \fill (5.95,0.4) circle (0.05);

  % 'Passive molecule'
  \filldraw[black!40!white] (0,-0.5) rectangle (6.4,-0.7);
  %bind site
  \draw[red] (0,-0.5) rectangle (1.6,-0.7);


\end{tikzpicture}
```

----
...and the second

```{r prefloodrep,engine='tikz',fig.width=10, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);
  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 2:}} Replicator reaction at t=600,000};

  % dividing line
  \draw[black!20!white] (-0.1,0) -- (6.5,0);

  %'ACTIVE MOL'
  \fill[black!40!white] (0,0.5) rectangle (2.8,0.7);
  % first scan loop:
  \fill[red!40!white] (0,0.5) rectangle (0.5,0.7);
  % 2nd scan loop:
  \fill[red!40!white] (1.2,0.5) rectangle (1.7,0.7);
  %bind site
  \draw[red] (0,0.5) rectangle (0.6,0.7);


  % 'Execution:' 
  \fill[green] (-0.1,0.4) circle (0.05);
  \fill[red] (0,0.4) circle (0.05);
  \draw[-> , draw=red] (0,0.4) -- (0.5,0.4); 
  \draw[->] (0.5,0.4) -- (1.2,0.4);

  \draw[->] (1.7,0.4) -- (2.0,0.4);
  \fill[red] (1.25,0.4) circle (0.05);
  \draw[-> , draw=red] (1.2,0.4) -- (1.7,0.4); 

  \fill (2.05,0.4) circle (0.05);

  % 'Passive molecule'
  \filldraw[black!40!white] (0,-0.5) rectangle (2.8,-0.7);
  %bind site
  \draw[red] (0,-0.5) rectangle (0.6,-0.7);

\end{tikzpicture}
```



```{r floodrep,engine='tikz',fig.width=10, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);
  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 3:}} Replicator reaction at t=680,000};

  % dividing line
  \draw[black!20!white] (-0.1,0) -- (6.5,0);


  %'Active molecule'
  \fill[black!40!white] (0,0.5) rectangle (3.8,0.7);
  % first scan loop:
  \fill[red!40!white] (0,0.5) rectangle (0.5,0.7);
  % toggle
  \fill[blue!40!white] (1.0,0.5) rectangle (1.2,0.7);
  % inactive loop:
  %\fill[red!40!white] (1.2,0.5) rectangle (1.7,0.7);
  % inactive loop:
  %\fill[red!40!white] (2.0,0.5) rectangle (2.5,0.7);
  % 2nd scan loop:
  \fill[red!40!white] (2.5,0.5) rectangle (3.0,0.7);
  %bind site
  \draw[red] (0,0.5) rectangle (0.6,0.7);

  % 'Execution:' 
  \fill[green] (-0.1,0.4) circle (0.05);
  \fill[red] (0,0.4) circle (0.05);
  \draw[-> , draw=red] (0,0.4) -- (0.5,0.4); 
  \draw[->] (0.5,0.4) -- (1.0,0.4);
  \draw[->] (1.0,0.4) -- (0,-0.4);
  \draw[->] (0,-0.4) -- (1.0,-0.4);
  \draw[->] (1.0,-0.4) -- (1.1,0.4);
  \draw[->] (1.1,0.4) -- (2.5,0.4);
  \fill[red] (2.55,0.4) circle (0.05);
  \draw[-> , draw=red] (2.5,0.4) -- (3.0,0.4); 
  \draw[->] (3.0,0.4) -- (3.4,0.4);
  \fill (3.45,0.4) circle (0.05);


  % 'Passive molecule'
  \filldraw[black!40!white] (0,-0.5) rectangle (3.8,-0.7);
  \fill[blue!40!white] (1.0,-0.5) rectangle (1.2,-0.7);

  %bind site
  \draw[red] (0,-0.5) rectangle (0.6,-0.7);

\end{tikzpicture}
```



```{r ffloodpar,engine='tikz',fig.width=10, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);
  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 4:}} Parasite resistance at t=1,080,000};
  % dividing line
  \draw[black!20!white] (-0.1,0) -- (6.5,0);



  %'Active molecule'
  \fill[black!40!white] (0,0.5) rectangle (3.8,0.7);
  % first scan loop:
  \fill[red!40!white] (0,0.5) rectangle (0.5,0.7);
  % toggle
  \fill[blue!40!white] (1.0,0.5) rectangle (1.2,0.7);
  % inactive loop:
  %\fill[red!40!white] (1.2,0.5) rectangle (1.7,0.7);
  % inactive loop:
  %\fill[red!40!white] (2.0,0.5) rectangle (2.5,0.7);
  % 2nd scan loop:
  \fill[red!40!white] (2.5,0.5) rectangle (3.0,0.7);
  %bind site
  \draw[red] (0,0.5) rectangle (0.6,0.7);



  % Execution: 
  \fill[green] (-0.1,0.4) circle (0.05);
  \fill[red] (0,0.4) circle (0.05);
  \draw[-> , draw=red] (0,0.4) -- (0.5,0.4); 
  \draw[->] (0.5,0.4) -- (1.0,0.4);
  \draw[->] (1.0,0.4) -- (0,-0.4);
  \draw[->] (0,-0.4) -- (1.1,-0.4);
  \fill[red] (1.15,-0.4) circle (0.05);
  \draw[-> , draw=red] (1.1,-0.4) -- (1.6,-0.4); 
  \draw[->] (1.6,-0.4) -- (2.2,-0.4);
  \fill (2.25,-0.4) circle (0.05);

  % Passive molecule
  \filldraw[black!40!white] (0,-0.5) rectangle (2.5,-0.7);
  \fill[red!40!white] (1.1,-0.5) rectangle (1.6,-0.7);

  %bind site
  \draw[red] (0,-0.5) rectangle (0.5,-0.7);

\end{tikzpicture}
```


```{r floodt3,engine='tikz',fig.width=10, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]
%\tikzset{>=latex}
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);
  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 5:}} Replicator reaction at t=1,500,000};
  % dividing line
  \draw[black!20!white] (-0.1,-0.1) -- (6.5,-0.1);

  % 'ACTIVE MOLECULE'
  \fill[black!40!white] (0,0.5) rectangle (3.4,0.7);
  % first scan loop:
  \fill[red!40!white] (0,0.5) rectangle (0.5,0.7);
  % toggle
  \fill[blue!40!white] (0.7,0.5) rectangle (0.9,0.7);
  % move
  \fill[green!40!white] (1.2,0.5) rectangle (1.4,0.7);
  % loop:
  \fill[red!40!white] (2.0,0.5) rectangle (2.4,0.7);
  % move
  \fill[green!40!white] (2.2,0.5) rectangle (2.4,0.7);
  % inactive loop:
  %\fill[red!40!white] (2.0,0.5) rectangle (2.5,0.7);
  % 2nd scan loop:
  %\fill[red!40!white] (3.1,0.5) rectangle (3.6,0.7);
  %bind site
  \draw[red] (0,0.5) rectangle (0.5,0.7);



  % 'Execution:' 
  \fill[green] (-0.1,0.4) circle (0.05);
  \fill[red] (0,0.4) circle (0.05);
  \draw[-> , draw=red] (0,0.4) -- (0.5,0.4); 
  \draw[->] (0.5,0.4) -- (0.7,0.4);

  %first toggle and back:
  \draw[->] (0.7,0.4) -- (0,-0.4);
  \draw[->] (0,-0.4) -- (0.7,-0.4);
  \draw[->] (0.7,-0.4) -- (0.8,0.4);

  %toggle at move: 
  \draw[->] (0.8,0.4) -- (1.2,0.4);
  \draw[->] (1.2,0.4) -- (1.2,0.3) -- (0.1,0.3);
  \draw[->] (0.1,0.3) -- (0.1,0.2) -- (0.7,0.2);
  \draw[->] (0.7,0.2) -- (0.8,-0.4);
  \draw[->] (0.8,-0.4) -- (1.2,-0.4);

  %second toggle at move 
  \draw[->] (1.2,-0.4) -- (0.1,0.1);
  \draw[->] (0.1,0.1) -- (0.7,0.1);
  \draw[->] (0.7,0.1) -- (1.3,-0.4);

  %toggle at second move and copy loop:
  \draw[->] (1.3,-0.4) -- (2.2,-0.4);
  \draw[->] (2.2,-0.4) -- (2.0,0.35);
  \draw[-> , draw=red] (2.0,0.4) -- (2.4,0.4); 
  \fill[red] (2.0,0.4) circle (0.05);
  
  %cleave and end
  \draw[->] (2.4,0.4) -- (2.95,0.4);
  \fill (3.0,0.4) circle (0.05);

  % 'Passive molecule'
  \fill[black!40!white] (0,-0.5) rectangle (3.4,-0.7);
  % first scan loop:
  \fill[red!40!white] (0,-0.5) rectangle (0.5,-0.7);
  % toggle
  \fill[blue!40!white] (0.7,-0.5) rectangle (0.9,-0.7);
  % move
  \fill[green!40!white] (1.2,-0.5) rectangle (1.4,-0.7);
  % loop:
  \fill[red!40!white] (2.0,-0.5) rectangle (2.4,-0.7);
  % move
  \fill[green!40!white] (2.2,-0.5) rectangle (2.4,-0.7);
  % inactive loop:
  %\fill[red!40!white] (2.0,-0.5) rectangle (2.5,-0.7);
  % 2nd scan loop:
  %\fill[red!40!white] (3.1,-0.5) rectangle (3.6,-0.7);
  %bind site
  \draw[red] (0,-0.5) rectangle (0.5,-0.7);

\end{tikzpicture}
```



```{r floodt6p, echo=FALSE, fig.width=10, message=FALSE, engine='tikz'}
\begin{tikzpicture}[font=\sffamily\tiny]
  %'canvas'
  \fill[black!5!white] (0,-1) rectangle (6.4,1.2);
  %Names
  \draw (0, 0.85) node[right] {String 1};
  \draw (0,-0.85) node[right] {String 2};

  %'title'
  \draw (2, 1) node[right]{\scriptsize {\bf{\sffamily 6:}} Parasitic reaction at t=2,000,000};
  % dividing line
  \draw[black!20!white] (-0.1,-0.1) -- (6.5,-0.1);



  % 'ACTIVE MOLECULE'
  \fill[black!40!white] (0,0.5) rectangle (0.7,0.7);
  % first scan loop:
  \fill[red!40!white] (0,0.5) rectangle (0.4,0.7);
  % toggle
  \fill[blue!40!white] (0.4,0.5) rectangle (0.6,0.7);
  %bind site
  \draw[red] (0,0.5) rectangle (0.3,0.7);



  % Execution: 
  \fill[green] (-0.1,0.4) circle (0.05);
  \fill[red] (0,0.4) circle (0.05);
  \draw[-> , draw=red] (0,0.4) -- (0.4,0.4); 
  \draw[->] (0.4,0.4) -- (0.45,0.4);
  \draw[->] (0.45,0.4) -- (0,-0.4);
  \draw[->] (0,-0.4) -- (1.0,-0.4);
  \draw[->] (1.0,-0.4) -- (0.1,0.3);
  \draw[->] (0.1,0.3) -- (0.45,0.3);
  \draw[->] (0.45,0.3) -- (1.1,-0.4);
  \draw[->] (1.1,-0.4) -- (1.5,-0.4);
  \draw[->] (1.5,-0.4) -- (0.1,0.2);
  %copy:
  \draw[-> , draw=red] (0,0.2) -- (0.4,0.2);   
  \fill[red] (0,0.2) circle (0.05);
  \draw[->] (0.4,0.2) -- (0.45,0.2);
  \draw[->] (0.45,0.2) -- (1.6,-0.4);
  \draw[->] (1.6,-0.4) -- (1.95,-0.4);
  \fill (2.0,-0.4) circle (0.05);

  % 'Passive molecule'
  \fill[black!40!white] (0,-0.5) rectangle (2.2,-0.7);
  % first scan loop:
  \fill[red!40!white] (0,-0.5) rectangle (0.4,-0.7);
  % toggle
  %\fill[blue!40!white] (0.7,-0.5) rectangle (0.9,-0.7);
  % move
  \fill[green!40!white] (1.0,-0.5) rectangle (1.2,-0.7);
  \fill[green!40!white] (1.5,-0.5) rectangle (1.7,-0.7);

\end{tikzpicture}
```



Here's the key to the tikz pictures: 

```{r tikzkey,engine='tikz',fig.width=20, message=F, echo=F}
\begin{tikzpicture}[font=\sffamily\tiny]

  %'canvas'
  \fill[black!5!white] (0,-0.1) rectangle (12.8,1);

  %Names
  \draw (0, 0.85) node[right] {KEY};

  % 'ACTIVE MOLECULE'
  \fill[black!40!white] (0.2,0.5) rectangle (0.4,0.7);
  \draw (0.5, 0.6) node[right] {Program};

  % 'bind site'
  \draw[red] (0.2,0.2) rectangle (0.4,0.4);
  \draw (0.5, 0.3) node[right] {Bind Site};

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % 'toggle'
  \fill[blue!40!white] (2.7,0.5) rectangle (2.9,0.7);
  \draw (3.0, 0.6) node[right] {Toggle};

  % 'move'
  \fill[green!40!white] (2.7,0.2) rectangle (2.9,0.4);
  \draw (3.0, 0.3) node[right] {Move};

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % 'loop':
  \fill[red!40!white] (5.2,0.5) rectangle (5.4,0.7);
  \draw (5.5, 0.6) node[right] {Loop};

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  % Execution start: 
  \fill[green] (7.7,0.6) circle (0.05);
  \draw (8.0, 0.6) node[right] {Program Entry Point};

  % Execution path:
  \draw[->] (7.6,0.3) -- (7.8,0.3);
  \draw (8.0, 0.3) node[right] {Execution path};

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  

  \fill[red] (10.1,0.6) circle (0.05);
  \draw[-> , draw=red] (10.1,0.6) -- (10.3,0.6); 
  \draw (10.4, 0.6) node[right] {Execution loop};

  % Execution end: 
  \fill[black] (10.2,0.3) circle (0.05);
  \draw (10.4, 0.3) node[right] {Program Exit};


\end{tikzpicture}
```

