# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwelve <- function(x) {
    .Call(`_Rstringmol_timesTwelve`, x)
}

#' Carry out a Smith-Waterman alignment
#'
#' @param input the input string (Assume error checking in R...)
#' @param verbose whether to print output or not
#' @export
doComplement <- function(input, verbose = FALSE) {
    .Call(`_Rstringmol_doComplement`, input, verbose)
}

#' Carry out a Smith-Waterman alignment
#'
#' @param seqVector the sequence of the two strings, active first, then passive.
#' @export
doSWAlign <- function(seqVector, strip = FALSE, verbose = FALSE) {
    .Call(`_Rstringmol_doSWAlign`, seqVector, strip, verbose)
}

#' React 2 stringmols together - determine whether the run is deterministic or not
#'
#' @param seqVector the sequence of the two strings, active first, then passive.
#' @export
doReaction <- function(seqVector, verbose = FALSE, climit = 1000L) {
    .Call(`_Rstringmol_doReaction`, seqVector, verbose, climit)
}

#' React 2 stringmols together - determine whether the run is deterministic or not - write to a file
#'
#' @param seqVector the sequence of the two strings, active first, then passive.
#' @export
doReactionFP <- function(seqVector, fnVector, verbose = FALSE) {
    invisible(.Call(`_Rstringmol_doReactionFP`, seqVector, fnVector, verbose))
}

